[project]
name = "flow_planning"
version = "0.1.0"
description = "Flow Planning Project"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
  "lerobot>=0.5.1",
  "newton[examples]",
  "pre-commit>=4.6.0",
  "rerun-sdk>=0.26.2",
  "scipy>=1.17",
  "slurm-tools",
  "torch>=2.11.0",
  "torchcodec>=0.12",
  "ty>=0.0.46",
  "wandb>=0.24.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
override-dependencies = ["torchcodec>=0.12", "torch>=2.11.0", "torchvision>=0.27"]

[tool.uv.sources]
torch = [{ index = "pytorch-cu126" }]
torchcodec = [{ index = "pytorch-cu126" }]
torchvision = [{ index = "pytorch-cu126" }]
slurm-tools = { git = "https://github.com/reeceomahoney/slurm-tools.git" }

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[tool.ruff.lint]
select = ["E", "F", "I"]
