[project]
name = "flow_planning"
version = "0.1.0"
description = "Flow Planning IsaacLab Project"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
  "lerobot>=0.5.1",
  "newton[examples]",
  "pre-commit>=4.6.0",
  "ty>=0.0.46",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
newton = { git = "https://github.com/newton-physics/newton.git", branch = "main" }

[tool.ruff.lint]
select = ["E", "F", "I"]
