strategy:
  type: base

inference:
  type: sync

robot:
  type: piper
  teleop_mode: false
  action_ema_alpha: 1.0
  clip_action: false
  action_bias_path: null
  apply_bias_to_obs: false
  arms: [right]

policy:
  path: reece-omahoney/piper-pick-and-place-aug
  n_action_steps: 30
  zero_cond: true
  dtype: bfloat16


fps: 20
task: Pick and place the pepper shaker
use_torch_compile: true
display_data: false
device: cuda
