name: flow-py

resources:
  infra: ssh/ori
  accelerators: RTX4090:0.5
  cpus: 4

envs:
  HF_TOKEN:
  CUDA_VISIBLE_DEVICES: 1
  MUJOCO_GL: egl
  CMAKE_POLICY_VERSION_MINIMUM: 3.5
  CMD: ""
workdir: .

run: |
  export PATH="$HOME/.pixi/bin:$PATH"
  export LD_LIBRARY_PATH="$PWD/.pixi/envs/default/lib:$LD_LIBRARY_PATH"
  bash -c "$CMD" 2>&1 | grep -vE "it/s\]|Warning|WARNING|macro"
