clusters:
  isambard:
    host: u6jz.aip2.isambard
    remote_path: /home/u6jz/reece.u6jz/flow-planning
    time: 12
    gpu: ""
    ngpu: 1
    cpus: 72
    mem: 1600M
    partition: workq

  arc:
    host: htc
    remote_path: /data/engs-robotics-ml/kebl6123/flow-planning
    time: 4
    gpu: h100
    ngpu: 1
    cpus: 24
    mem: 8G
    partition: short
    priority: true

  civo:
    host: civo
    remote_path: /users/kebl6123/flow-planning
    time: 12
    gpu: nvidia_b200
    ngpu: 1
    cpus: 27
    mem: 11G
    partition: allgpus

# envs:
#   - WANDB_API_KEY
#   - HF_TOKEN
#   - PYTORCH_CUDA_ALLOC_CONF: expandable_segments:True
#
#   # cpu thread limits
#   - OPENBLAS_NUM_THREADS: 8
#   - OMP_NUM_THREADS: 8
#   - MKL_NUM_THREADS: 8
#
#   # cache directories
#   - TORCHINDUCTOR_CACHE_DIR: $HOME/.cache/torchinductor
#   - TRITON_CACHE_DIR: /scratch/u6jz/reece.u6jz/.cache/triton
#   - UV_PROJECT_ENVIRONMENT: /scratch/u6jz/reece.u6jz/flow-planning/.venv
#   - UV_CACHE_DIR: /scratch/u6jz/reece.u6jz/.cache/uv
#   - HF_HOME: /scratch/u6jz/reece.u6jz/.cache/huggingface
#   - RATTLER_CACHE_DIR: /scratch/u6jz/reece.u6jz/.cache/rattler

command: |-
  nvidia-smi
